name = "quizhp-mcp"
main = "dist/server/worker.js"
compatibility_date = "2024-12-01"
account_id = "e0495ef26972403d37cdae7e9e807ed2"

routes = [
  { pattern = "mcp.quizhp.com/*", zone_name = "quizhp.com" }
]
